### ISSUE TITLE
Add MACD

### ISSUE THREAD

**Issue by aminmarashi** [binary-com/binary-bot#131]
- [x] Add MACD (binary-com/binary-indicators#6)
- [x] Add to Binary Charts (binary-com/binary-charts#179)
- [x] Add to Binary Bot (#136)
