### ISSUE TITLE
Major refactor to add jsi, makes the trading easily testable and more reliable

### ISSUE THREAD

**Issue by aminmarashi** [binary-com/binary-bot#90]
Our current tests are very complex we need to:
- [x] Remove UI elements from tests (make pure logic modules) (#144)
  - [x] Separate translator to `lang` and `i18n` (#117) 
- [x] Add JS-Interpreter (#155)
- [x] Convert current tests to a simple expected/got comparison
- [x] Simplify the bot interface for talking with blocks
- [x] Bind Stop/Start controls to JSI Stop/Start
- [x] Make chart stream independent from stop/start
- [x] Bot Error (#158)
- [x] Add limitations and test reality check
- [x] Provide additional context for the Tick Analysis blocks (#152)
- [x] Fix `Change By` Block
- [ ] Add Pause/Resume controls
- [ ] Add more tests to cover more types of trades
- [ ] Make indicator block tests
- [ ] Add sanitizers for the remaining blocks
- [x] Add default (shadowed) blocks

**Comment by aminmarashi** [comment]
Separate translator to lang and i18n #117

**Comment by Adezking** [comment]
Hello @Krishna,can you help with this?I want to connect my app_id obtained after registering my bot on Binary.com to their WebSocket API for auto trading and I was told I need a system build.

Please I need a step-by-step guide on how to build a system with Binary.com API Library on GitHub or a link to an already built system.
Pls you can contact me at adezking2007@gmail.com and we can even talk business
Thank you sir.

**Comment by gokula-krishna-dev** [comment]
Hi @Adezking please refer this thread https://github.com/binary-com/binary-bot/issues/636. Let me know if you need further help.
